### ISSUE TITLE
iOS issue

### ISSUE THREAD

**Issue by mtvg** [sretlawd/augustctl#1]
Not sure if it works with an iOS offline key, the offline key is available at this path: 
```
/private/var/mobile/Containers/Data/Application/5BDACAAE-C7D1-40F8-A02C-5CBEE55DA91C/Library/Preferences/com.august.iossapp.plist
```
You need a jailbroken device to access it.

But then it doesn't seem to work, the script (running on OS X) gets stuck after this:
```
 august:lock connected. +731ms
 august:lock_session enabling indications on 42 +2ms
 august:lock_session enabling indications on 35 +0ms
 august:lock_session execute command: 010000009b2fa9378ef3b60dd6dc9fba0f01 +2ms
 august:lock_session write (encrypted): c55fa6a17c7a380cc0f97eb653ff4b410f01 +0ms
 august:lock_session write successful, waiting for notification... +1ms
```

I'm gonna try to get an offline key on an Android device to see if it works better.

Thanks for sharing your code though! :+1:

**Comment by sretlawd** [comment]
Hi Mathieu!  Can you try the v0.0.1 tag and see if it works for you?  It looks like I pushed my master without realizing, and due to circumstances I havn't actually tested 86f7230571b146690c14d523caec94c4185b6f0b yet, which is very very likely the problem you're seeing.  Can't tell you how cool it is that somebody else is interested in this!  :smile:

**Comment by sretlawd** [comment]
OK, I rolled master back to what I know works and put all the code cleanup on the wip branch until I can get it fixed!

**Comment by mtvg** [comment]
Awesome, yes, it works great! Really appreciate your help, I'll be finally able to control my August through internet.
If you still working on it, a nice new feature would be to get the lock status of the lock! But yeah, great work! 
Thanks!

**Comment by mtvg** [comment]
FYI: you don't need a jailbroken iOS device to get the offlinekey after all.
Just use a file explorer like http://www.i-funbox.com/ifunboxmac/
Then go to `User Applications/August/Library/Preferences/com.august.iossapp.plist` and open the `.plist` with xcode.

**Comment by sretlawd** [comment]
OK, I think I got all my refactoring actually working!  Thanks for figuring out how to get the keys off of an iPhone, I added information on it to the README.
