### ISSUE TITLE
OSX Install issue

### ISSUE THREAD

**Issue by nelemansc** [sretlawd/augustctl#2]
Thanks for putting this together! I'm attempting to integrate the August lock with SmartThings since the official integration is TBD, and this is just what I was looking for. Unfortunately I can't get the module to fire.

Noble install

> cpn:node_modules admin$ npm install noble
> npm WARN optional dep failed, continuing bluetooth-hci-socket@0.3.2
> -
> xpc-connection@0.1.3 install /Users/admin/node_modules/noble/node_modules/xpc-connection
> node-gyp rebuild

>  CXX(target) Release/obj.target/binding/src/XpcConnection.o
>  SOLINK_MODULE(target) Release/binding.node
>  SOLINK_MODULE(target) Release/binding.node: Finished
> noble@1.1.0 noble
> âââ bplist-parser@0.0.6
> âââ debug@2.2.0 (ms@0.7.1)
> âââ xpc-connection@0.1.3 (nan@1.9.0)

augustctl install
> cpn:node_modules admin$ npm install augustctl
> |
> xpc-connection@0.1.3 install /Users/admin/node_modules/augustctl/node_modules/noble/node_modules/xpc-connection
> node-gyp rebuild

>   CXX(target) Release/obj.target/binding/src/XpcConnection.o
>   SOLINK_MODULE(target) Release/binding.node
>   SOLINK_MODULE(target) Release/binding.node: Finished

> noble@0.3.14 install /Users/admin/node_modules/augustctl/node_modules/noble
> node-gyp rebuild

>   LINK(target) Release/hci-ble
>   LINK(target) Release/hci-ble: Finished
>   LINK(target) Release/l2cap-ble
>   LINK(target) Release/l2cap-ble: Finished
> augustctl@0.1.0 augustctl
> âââ debug@2.2.0 (ms@0.7.1)
> âââ morgan@1.6.1 (basic-auth@1.0.3, on-headers@1.0.0, depd@1.0.1, on-finished@2.3.0)
> âââ bluebird@2.9.34
> âââ express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, >cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, meth                                 ods@1.1.1, > fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, path-to-regexp@0.1.7, etag@1.7.0, content->type@1.0.1, parseurl@1.3.0, content-disposition@                                 0.5.0, serve-static@1.10.0, depd@1.0.1, on-finished@2.3.0, qs@4.0.0, finalhandler@0.4.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.6, accepts@1.2                                 .12)
âââ noble@0.3.14 (debug@0.7.4, bplist-parser@0.0.6, xpc-connection@0.1.3)

When executing augustctl from terminal I get "command not found". Do I have to be in a certain dir? I have tried it when in the augustctl dir (/Users/admin/node_modules/augustctl) but still no luck. 

Right now config.json is in the augustctl dir (/Users/admin/node_modules/augustctl) with the my iPhone offlineKey. I was unable to locate the offlineKeyOffset in plist so I made an assumption that mine is "1".

config.json contains the following:
> { "offlineKey": "123456789abcdefghijklmnopqrstuvw", "offlineKeyOffset": 1 }

Any help would be greatly appreciated!

**Comment by sretlawd** [comment]
It looks like the "latest compatible" version of noble (0.9.14) doesn’t install quite right, so I just bumped all dependencies to the very latest versions with efc61ea15307016b010d2fe868bdf1eaf5c9110d .  It now gets through the npm install OK.  The problem is, I’m not at home where I can actually try it out, so I have no idea if it still works.  I'll be home this weekend and can verify/fix it then.

Regarding command not found, I guess I need to work on the instructions a bit, try:

  npm install -g augustctl

which should put it in /usr/local/bin, and then run augustctl from the same directory as your config.json.  It's just the cli.js script, which you can also run directly if you checked out the project via git.

**Comment by sretlawd** [comment]
OK, I just verified that it actually still works with all the updated dependencies, and also added a npm shrinkwrap so that this sort of thing shouldn't pop up in the future.
